server:
  port: 7010
spring:
  mail:
    #email
    #SMTP\u670D\u52A1\u5668\u7684\u540D\u5B57
    host: smtp.mxhichina.com
    #\u53D1\u9001\u4EBA\u90AE\u7BB1\u540D\u79F0
    username: xxxx@qq.com
    #\u90AE\u7BB1\u5BC6\u7801\uFF0C\u8FD9\u91CC\u6307\u7684\u662F\uFF0C\u5728\u90AE\u7BB1\u4E2D\u6253\u5F00SMTP/POP3\u9A8C\u8BC1\u4E4B\u540E\uFF0C\u4F1A\u7ED9\u51FA\u4E00\u4E2A\u9A8C\u8BC1\u7801
    password: 123456
    #\u7F16\u7801\u683C\u5F0F
    default-encoding: UTF-8
    #SMTP\u670D\u52A1\u5668\u5F00\u653E\u7684\u7AEF\u53E3
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
